dataset_path: "../../Report-nmi-wsi"
histocartography_path: "../histocartography/histocartography"
graph_path: "graph"
output_path: "output"
vocab_path: "../../Report-nmi-wsi/vocab_bladderreport.pkl"
learning_rate: 0.001
phase: train # train, test, eval
batch_size: batch_size
epochs: 4
graph_model_type: "Hierarchical" #  Hierarchical, Cell, Tissue
batch_size: 4

gnn_param:
  cell_layers: 2
  tissue_layers: 2
  cell_conv_method: "GIN" # GCN, GAT, GraphSage, GIN, PNA
  tissue_conv_method: "GIN" # GCN, GAT, GraphSage, GIN, PNA
  pool_method: None # None, Diff, MinCut
  aggregate_method: "sum" # sum, mean


lstm_param:
  dropout: 0.5

