dataset_path: "../../Report-nmi-wsi"
histocartography_path: "../histocartography/histocartography"
graph_path: "full-graph"
output_path: "output"
vocab_path: "../../Report-nmi-wsi/vocab_bladderreport.pkl"
learning_rate: 0.001
phase: train # train, test, eval
epochs: 3
graph_model_type: "Hierarchical" #  Hierarchical, Cell, Tissue
batch_size: 64

gnn_param:
  cell_layers: 2
  tissue_layers: 2
  cell_conv_method: "GCN" # GCN, GAT, GraphSage, GIN, PNA
  tissue_conv_method: "GCN" # GCN, GAT, GraphSage, GIN, PNA
  pool_method: None # None, Diff, MinCut
  aggregate_method: "max" # sum, mean, max


lstm_param:
  dropout: 0.5

